#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Touch,          sensorTouch)
#pragma config(Motor,  motorA,          leftFront,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftBack,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightFront,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightBack,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot() {
	if(SensorValue(Touch) == 1) {
		nMotorEncoder[leftFront] = 0;
		nMotorEncoder[leftBack] = 0;
		while(nMotorEncoder[leftFront] < 1380 && nMotorEncoder[leftBack] < 1380) {
				motor[leftFront] = 85;
				motor[leftBack] = 85;
				motor[rightFront] = -85;
				motor[rightBack] = -85;
		}
	}
  return;
}

task main() {
  initializeRobot();
  waitForStart();
  while (true) {

  }
}
