#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          leftFront,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftBack,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
bool ramp = false;

void turn(int degree, int power, bool leftDir) {
	nMotorEncoder[leftFront] = 0;
	nMotorEncoder[leftBack] = 0;
	int stopTurn = 1380; //encoderTick/1 degree * degree var
	if(leftDir) {
		while(nMotorEncoder[leftFront] < stopTurn && nMotorEncoder[leftBack] < stopTurn) {
			motor[leftFront] = power;
			motor[leftBack] = power;
			motor[rightFront] = power * -1;
			motor[rightBack] = power * -1;
		}
	} else {
			while(nMotorEncoder[leftFront] < stopTurn && nMotorEncoder[leftBack] < stopTurn) {
				motor[leftFront] = power * -1;
				motor[leftBack] = power * -1;
				motor[rightFront] = power;
				motor[rightBack] = power;
		}
	}
}

void initializeRobot() {
	if(SensorValue[Sonar] < 20) {
		turn(90, 90, true);
		ramp = true;
	}
  return;
}

task main() {
	initializeRobot();
  waitForStart();
  if(ramp) {
		while (nMotorEncoder[leftFront] < 8.57 && nMotorEncoder[leftBack] < 8.57 && nMotorEncoder[rightFront] < 8.75 && nMotorEncoder[rightBack] < 8.75) {
			motor[leftFront] = 85;
			motor[leftBack] = 85;
			motor[rightFront] = 85;
			motor[rightBack] = 85;
		}
		//TODO: Grab 60cm rolling goal
		while (nMotorEncoder[leftFront] < 5.7 && nMotorEncoder[leftBack] < 5.7 && nMotorEncoder[rightFront] < 5.7 && nMotorEncoder[rightBack] < 5.7) {
			motor[leftFront] = -85;
			motor[leftBack] = -85;
			motor[rightFront] = -85;
			motor[rightBack] = -85;
		}
		turn(90, 90, true);
		while (nMotorEncoder[leftFront] < 3.7 && nMotorEncoder[leftBack] < 3.7 && nMotorEncoder[rightFront] < 3.7 && nMotorEncoder[rightBack] < 3.7) {
			motor[leftFront] = 85;
			motor[leftBack] = 85;
			motor[rightFront] = 85;
			motor[rightBack] = 85;
		}
		turn(90, 90, true);
		while (nMotorEncoder[leftFront] < 2.9 && nMotorEncoder[leftBack] < 2.9 && nMotorEncoder[rightFront] < 2.9 && nMotorEncoder[rightBack] < 2.9) {
			motor[leftFront] = 85;
			motor[leftBack] = 85;
			motor[rightFront] = 85;
			motor[rightBack] = 85;
		}
	}
}
