#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          leftFront,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftBack,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_1, rightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, scissorFront,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, grabber,              tServoContinuousRotation)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotFunctions.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot() {
  servo[grabber] = 127;
}

task main() {
	initializeRobot();
	waitForStart();
	move(9 * 12, 90);
	wait1Msec(300);
	moveScissorLiftPos(60);
	dropBallInGoal();
	turn(90, 90, true);
	move(2 * 12, 90);
	wait1Msec(300);
	turn(90, 90, true);
	wait1Msec(300);
	move(1 * 12, -90);
	wait1Msec(300);
	moveScissorLiftPos(30);
	dropBallInGoal();
	grabRollingGoal();
	move(10 * 12, 90);
	wait1Msec(300);
	turn(90, 90, false);
	move(1 * 12, 90);
	releaseRollingGoal();
}

finishActionDefs();
