#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          leftFront,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftBack,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot() {
  return;
}

task main() {
  initializeRobot();
  waitForStart();
  while (true) {
  	getJoystickSettings(joystick);
  	if(abs(joystick.joy1_y1) > 10) {
	    motor[leftFront] = joystick.joy1_y1;
	    motor[leftBack] = joystick.joy1_y1;
	    motor[rightFront] = joystick.joy1_y1;
	    motor[rightBack] = joystick.joy1_y1;
		}
    getJoystickSettings(joystick);
    if(joystick.joy1_y1 > 10) {
    	motor[leftFront] = joystick.joy1_y1;
    	motor[leftBack] = joystick.joy1_y1;
    	motor[rightFront] = joystick.joy1_y1;
    	motor[leftFront] = joystick.joy1_y1;
  	}
	}
}
